#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [0]:
import numpy as np

arr1 = np.array((7, 8, 4, 5, 1, 2))
print(arr1)

[7 8 4 5 1 2]


Using slicing print the elements from index 3 to the end of the array.



In [0]:
print(arr1[3:])

[5 1 2]


Using slicing print all the elements except the last one.



In [0]:
print(arr1[:-1])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [0]:
print(arr1[1:5])

[8 4 5 1]


Reshape the array into a 3 rows and 2 cols (3,2).



In [0]:
newarr = arr1.reshape(3, 2)
print(newarr)

[[7 8]
 [4 5]
 [1 2]]


Print all the array elements one by one (iterating).



In [0]:
for x in arr1:
  print (x)


7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [0]:
arr2= np.array((0,6,9))
print (arr2)

[0 6 9]


Join the two arrays.



In [0]:
arr = np.concatenate((arr1, arr2))
print (arr)

[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [0]:
#Filter to select odd numbers
filter_arr = arr % 2 == 1

newarr = arr[filter_arr]
print(arr)
print(filter_arr)
print(newarr)

[7 8 4 5 1 2 0 6 9]
[ True False False  True  True False False False  True]
[7 5 1 9]


Sort the joined array elements.



In [0]:
sortarr=(np.sort(arr))
print(sortarr)

[0 1 2 4 5 6 7 8 9]



Store in an array the names of the months.


In [0]:
months=np.array(('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'))
print(months)

['January' 'February' 'March' 'April' 'May' 'June' 'July' 'August'
 'September' 'October' 'November' 'December']


Split the months array in 4 periods of 3 elements each one.



In [0]:
period = months.reshape(4, 3)
print (period)

[['January' 'February' 'March']
 ['April' 'May' 'June']
 ['July' 'August' 'September']
 ['October' 'November' 'December']]


Create an array with genre information ['F','M','F','F','M','F'].



In [0]:
genre=np.array(('F','M','F','F','M','F'))
print(genre)

['F' 'M' 'F' 'F' 'M' 'F']


Find the indexes where the value is F.



In [0]:
arregloF = np.where(genre=='F')

print(arregloF)

(array([0, 2, 3, 5]),)


Store in an array the age information [18,20,19,23,19,20].



In [0]:
age=np.array((18,20,19,23,19,20))
print(age)

[18 20 19 23 19 20]


Create a filter array with values < 20.



In [0]:
filter_arr = age < 20

newarr = age[filter_arr]

print(newarr)

[18 19 19]


Change the 3 index element with a value of 22



In [0]:
age=age.view()
age[3]=22
print(age)

[18 20 19 22 19 20]


Print the 4 index element.

In [0]:
print(age[4])

19
